print('this is class 01')
print('this is class 02')
print('this is class 03')
print('getting data in 4 hours')  
print('this is class 05')
print('this is class 06')
print('this is class 07')
print('this is class 08')
print('this is class 09')
print('this is class 10')